#autogenerated by sqlautocode

from sqlalchemy import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relation

engine = create_engine('postgresql://metaperl:m0ney123@localhost/focus')
DeclarativeBase = declarative_base()
metadata = DeclarativeBase.metadata
metadata.bind = engine

try:
    from sqlalchemy.dialects.postgresql import *
except ImportError:
    from sqlalchemy.databases.postgres import *
alembic_version = Table(u'alembic_version', metadata,
    Column(u'version_num', VARCHAR(length=32), nullable=False),
)

class Affiliate(DeclarativeBase):
    __tablename__ = 'affiliate'

    __table_args__ = {}

    #column definitions
    email = Column(u'email', VARCHAR(length=128), nullable=False)
    id = Column(u'id', VARCHAR(length=128), primary_key=True, nullable=False)
    kbuk_id = Column(u'kbuk_id', INTEGER())
    name = Column(u'name', VARCHAR(length=128), nullable=False)
    number = Column(u'number', VARCHAR(length=128), nullable=False)
    pic = Column(u'pic', VARCHAR(length=512))
    skype = Column(u'skype', VARCHAR(length=128))

    #relation definitions

